import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { PostCardList } from '@/components/organisms/PostCardList';
import { Pagination } from '@/components/organisms/Pagination';
import {
  withSidebar,
  WithSidebarProps,
  getStaticProps,
} from '@/containers/withSidebar';

type QueryParams = {
  page?: string;
};

type Props = WithSidebarProps;

const NUMBER_OF_POST_PER_PAGE = 10;

const IndexPage: NextPage<Props> = ({ posts }) => {
  const router = useRouter();
  const queryParams = router.query as QueryParams;
  const page =
    queryParams.page && queryParams.page.length > 0
      ? parseInt(queryParams.page, 10)
      : 1;

  const startIndex = NUMBER_OF_POST_PER_PAGE * (page - 1);
  const postsForDisplay = posts.slice(
    startIndex,
    startIndex + NUMBER_OF_POST_PER_PAGE
  );

  return (
    <div>
      <Head>
        <title>トップページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid md:grid-cols-2 gap-6">
        <PostCardList posts={postsForDisplay} />
      </div>

      <div className="mt-10">
        <Pagination
          perPage={NUMBER_OF_POST_PER_PAGE}
          total={posts.length}
          currentPage={page}
        />
      </div>
    </div>
  );
};

export { getStaticProps };

export default withSidebar(IndexPage);
